analytics: {}
color:
  brandColors:
    - '#FEFEFE'
    - '#D9D9D9'
    - '#020202'
    - '#DE0323'
    - '#878787'
  brandStrength: 0.625449
  lightness: 0.092928
  rhythmicContrast: 0.567703
  saturation: 0.243395
cta: {}
layout_spectrum: 0.749178
name: gase
opengraph: {}
purpose: {}
typography_spectrum: 0.624178
