name: gase
favicon: null
layout_spectrum: 0.749178
typography_spectrum: 0.624178
title: General Aviation Support Egypt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#D9D9D9'
    - '#020202'
    - '#DE0323'
    - '#878787'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
